image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - test
  - deploy

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'HalfAndHalf/'
  DEPLOY_PATH: '/home/${USER}/HalfAndHalf'

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - "${SOURCE_CODE_PATH}${OBJECTS_DIRECTORY}/project.assets.json"
    - "${SOURCE_CODE_PATH}${OBJECTS_DIRECTORY}/*.csproj.nuget.*"
    - "${NUGET_PACKAGES_DIRECTORY}"
  policy: pull-push

before_script:
  - cd ${SOURCE_CODE_PATH}
  - dotnet restore --packages ${NUGET_PACKAGES_DIRECTORY}

build:
  stage: build
  script:
    - dotnet build --no-restore
    - dotnet publish -c Release -o ../publish
  artifacts:
    paths:
      - publish/
      - ${SOURCE_CODE_PATH}bin/
      - ${SOURCE_CODE_PATH}obj/

tests:
  stage: test
  script:
    - dotnet test --no-restore

deploy-server0:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY_HALF_SVR0" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_HOST0 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # Create directory and copy entire project
    - ssh ${USER}@$DEPLOY_HOST0 "mkdir -p ${DEPLOY_PATH}"
    - tar czf project.tar.gz -C .. .
    - scp project.tar.gz ${USER}@$DEPLOY_HOST0:${DEPLOY_PATH}/
    - ssh ${USER}@$DEPLOY_HOST0 "cd ${DEPLOY_PATH} && tar xzf project.tar.gz && rm project.tar.gz"
  only:
    - main
  environment:
    name: production-server0