image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - test
  - deploy

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'FinalProject/HalfAndHalf/'

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - "${SOURCE_CODE_PATH}${OBJECTS_DIRECTORY}/project.assets.json"
    - "${SOURCE_CODE_PATH}${OBJECTS_DIRECTORY}/*.csproj.nuget.*"
    - "${NUGET_PACKAGES_DIRECTORY}"
  policy: pull-push

before_script:
  - cd ${SOURCE_CODE_PATH}
  - dotnet restore --packages ${NUGET_PACKAGES_DIRECTORY}

build:
  stage: build
  script:
    - dotnet build --no-restore
  artifacts:
    paths:
      - ${SOURCE_CODE_PATH}bin/
      - ${SOURCE_CODE_PATH}obj/

tests:
  stage: test
  script:
    - dotnet test --no-restore

deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY_HALF_SVR0}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan -H 10.200.12.179 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh ${DEPLOY_USER}@10.200.12.179 '/home/${DEPLOY_USER}/scriptToPull.sh'
    - ssh ${DEPLOY_USER}@10.200.12.179 hostname
    - ssh ${DEPLOY_USER}@10.200.12.179 w
  only:
    - main
  environment: production