image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - test
  - deploy

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'HalfAndHalf/'
  DEPLOY_PATH: '/home/${DEPLOY_USER}/FinalProject'
  ANSIBLE_PROJECT_PATH: 'ansible_project'
  ANSIBLE_HOST_KEY_CHECKING: 'False'

before_script:
  - cd ${SOURCE_CODE_PATH}
  - dotnet restore --packages ${NUGET_PACKAGES_DIRECTORY}

build:
  stage: build
  script:
    - dotnet build --no-restore
    - dotnet publish -c Release -o ../publish
  artifacts:
    paths:
      - publish/
      - dockerfile
      - ansible_project/
      - inventory.ini
      - nrc-20250203.sql

tests:
  stage: test
  script:
    - dotnet test --no-restore

deploy:
  stage: deploy
  script:
    # Debug information
    - |
      echo "Current directory: $(pwd)"
      cd ..
      echo "Parent directory contents:"
      ls -la
      echo "Checking for ansible files:"
      ls -la ansible_project/playbooks/
      ls -la inventory.ini

    # SSH setup
    - |
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh
      echo "$SSH_PRIVATE_KEY_HALF_SVR0" | tr -d '\r' > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      ssh-keyscan -H $DEPLOY_HOST0 >> ~/.ssh/known_hosts
      chmod 644 ~/.ssh/known_hosts

    # Deploy with ignore unreachable
    - |
      echo "Starting deployment..."
      ssh ${DEPLOY_USER}@$DEPLOY_HOST0 "
        cd ${DEPLOY_PATH} && \
        git pull && \
        echo 'Successfully pulled from main branch' && \
        export ANSIBLE_HOST_KEY_CHECKING=False && \
        ansible-playbook -i inventory.ini ansible_project/playbooks/ping.yml --ignore-unreachable -vv || true
      "
  only:
    - main
  environment:
    name: production