image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - test
  - deploy

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'HalfAndHalf/'
  DEPLOY_USER: 'deployuser1'
  DEPLOY_HOST0: '10.200.12.179'

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - "${SOURCE_CODE_PATH}${OBJECTS_DIRECTORY}/project.assets.json"
    - "${SOURCE_CODE_PATH}${OBJECTS_DIRECTORY}/*.csproj.nuget.*"
    - "${NUGET_PACKAGES_DIRECTORY}"
  policy: pull-push

before_script:
  - cd ${SOURCE_CODE_PATH}
  - dotnet restore --packages ${NUGET_PACKAGES_DIRECTORY}

build:
  stage: build
  script:
    - dotnet build --no-restore
  artifacts:
    paths:
      - ${SOURCE_CODE_PATH}bin/
      - ${SOURCE_CODE_PATH}obj/

tests:
  stage: test
  script:
    - dotnet test --no-restore

deploy:
  stage: deploy
  image: fedora:latest
  before_script:
    - dnf install -y openssh-clients
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY_HALF_SVR0" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_HOST0 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -i ~/.ssh/id_rsa ${DEPLOY_USER}@${DEPLOY_HOST0} '/home/'${DEPLOY_USER}'/scriptToPull.sh'
    - ssh -i ~/.ssh/id_rsa ${DEPLOY_USER}@${DEPLOY_HOST0} 'hostname'
    - ssh -i ~/.ssh/id_rsa ${DEPLOY_USER}@${DEPLOY_HOST0} 'w'
  only:
    - main
  environment: production