image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - test
  - deploy

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'HalfAndHalf/'
  DEPLOY_PATH: '/home/${DEPLOY_USER}/FinalProject'
  ANSIBLE_PROJECT_PATH: 'ansible_project'
  ANSIBLE_HOST_KEY_CHECKING: 'False'

before_script:
  - cd ${SOURCE_CODE_PATH}
  - dotnet restore --packages ${NUGET_PACKAGES_DIRECTORY}
  - apt-get update && apt-get install -y openssh-client

build:
  stage: build
  script:
    - dotnet build --no-restore
    - dotnet publish -c Release -o ../publish
  artifacts:
    paths:
      - publish/
      - dockerfile
      - ${ANSIBLE_PROJECT_PATH}/
      - nrc-20250203.sql
      - inventory.ini

deploy:
  stage: deploy
  script:
    # Setup SSH access
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY_HALF_SVR0" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - |
      # Add host keys for server 0 and 1
      ssh-keyscan -H $DEPLOY_HOST0 >> ~/.ssh/known_hosts
      ssh-keyscan -H $DEPLOY_HOST1 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Deploy to control node and run ping test
    - |
      ssh ${DEPLOY_USER}@$DEPLOY_HOST0 "
        cd ${DEPLOY_PATH} && \
        git pull && \
        echo 'Running ping test...' && \
        ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.ini ansible_project/playbooks/ping.yml -vv
      "
  only:
    - main
  environment:
    name: production