---
- hosts: load_balancer
  become: yes
  tasks:
    - name: Configure HAProxy
      template:
        src: ../templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
      notify: Restart HAProxy

    - name: Ensure HAProxy is running
      systemd:
        name: haproxy
        state: started
        enabled: yes

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted

- hosts: webservers
  become: yes
  tasks:
    - name: Open port 5000 in firewall
      firewalld:
        port: 5000/tcp
        permanent: yes
        state: enabled
      notify: Reload Firewall

  handlers:
    - name: Reload Firewall
      command: firewall-cmd --reload
